/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/api-tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_api_tools"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/api-tools/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_api_tool"];
        put: operations["put_api_tool"];
        post?: never;
        delete: operations["delete_api_tool"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_chats"];
        put?: never;
        post: operations["post_create_chat"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_chat"];
        put?: never;
        post?: never;
        delete: operations["delete_chat"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live subscription to a chat's *agent-initiated* turns (scheduled follow-ups).
         *     The workshop opens this when a chat is on screen so a follow-up that fires
         *     while the user is idle streams in without a page refresh. Normal
         *     user-initiated turns still come back on their own `POST .../turn` response.
         */
        get: operations["get_chat_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/chats/{id}/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run one turn against the chat session. Streams new messages as Server-Sent
         *     Events as the agent steps; closes the connection when the executor returns.
         */
        post: operations["post_chat_turn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_diagnostics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_diagnostics_session"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flow-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted flow runs, optionally filtered by `?flow_id=`. */
        get: operations["list_flow_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flow-runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one flow run by id. */
        get: operations["get_flow_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flow-runs/{run_id}/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume a paused flow run. */
        post: operations["post_resume_flow_run"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flow-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_flow_templates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flow-templates/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_flow_template"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flows/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_flow"];
        put: operations["put_flow"];
        post?: never;
        delete: operations["delete_flow"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/flows/{id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["post_run_flow"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Recent gateway activity across all channels, including inbound messages that
         *     matched no channel (the global Network view). Newest first.
         */
        get: operations["list_gateway_activity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/channels": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all configured gateway channel instances. */
        get: operations["list_gateway_channels"];
        put?: never;
        post: operations["post_create_gateway_channel"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/channels/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_gateway_channel"];
        post?: never;
        delete: operations["delete_gateway_channel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/channels/{id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_gateway_channel_enabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/channels/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent inbound/outbound activity for a single channel (newest first). */
        get: operations["list_gateway_channel_events"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/metalcraft/connect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Connect: fetch config + wire the webhook + enable the channel. 409 until verified. */
        post: operations["gateway_metalcraft_connect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/metalcraft/disconnect": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disconnect: disable the metalcraft-gateway channel + drop its secrets. Idempotent. */
        post: operations["gateway_metalcraft_disconnect"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/metalcraft/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Inline register: proxy to the gateway with the pod's token; returns `verify_code`. */
        post: operations["gateway_metalcraft_register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/metalcraft/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Registration/verification/connection state for the workshop's Connect panel. */
        get: operations["gateway_metalcraft_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/gateway/types": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the installed gateway channel types (with their per-instance settings
         *     schema), so the workshop can render a "new channel" form.
         */
        get: operations["list_gateway_types"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Agent identity/version + config the Workshop reads. `version` drives the
         *     Settings tab's "which build is live" check; `default_persona` is the persona
         *     the Workshop's New Chat modal defaults to (set `METALCRAFT_DEFAULT_PERSONA`
         *     to override; falls back to the orchestrator, which delegates to specialists).
         */
        get: operations["agent_info"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration-packs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_integration_packs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration-packs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_integration_pack"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/integration-packs/{id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put: operations["put_pack_enabled"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_keys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/recommended": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Keys recommended by enabled packs, each flagged configured/missing. Lets the
         *     key store UI surface "these enabled packs need these keys" without the user
         *     having to read each pack's manifest.
         */
        get: operations["list_recommended_keys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upsert a key. The name comes from the path; the raw value (and an optional
         *     target `channel_id`) from the body. Managed keys — a platform-injected global
         *     (env-authoritative) or a provisioner-backed channel's secrets — are read-only
         *     and rejected here.
         */
        put: operations["put_key"];
        post?: never;
        /**
         * Delete a key. An optional `?channel_id=` targets a channel's secret scope;
         *     omitted means the global scope. Managed keys are read-only and rejected.
         */
        delete: operations["delete_key"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/keys/{name}/reveal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Reveal a stored key's **raw** value. An optional `?channel_id=` targets a
         *     channel's secret scope; omitted means global. This is the one endpoint that
         *     returns an unmasked value — an explicit, user-initiated action in the Keys UI.
         *     Only returns values physically present in the store (a derived/env-only value
         *     like a provisioner's `API_KEY` is not stored, so there's nothing to reveal).
         */
        get: operations["reveal_key"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/personas/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_persona"];
        put: operations["put_persona"];
        post?: never;
        delete: operations["delete_persona"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduled-tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List scheduled follow-ups (pending + recently completed), newest first. */
        get: operations["list_scheduled_tasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scheduled-tasks/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Cancel a pending scheduled follow-up. */
        delete: operations["delete_scheduled_task"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/skills/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_skill"];
        put: operations["put_skill"];
        post?: never;
        delete: operations["delete_skill"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_snapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiToolSummary: {
            description: string;
            name: string;
            pack_id?: string | null;
            read_only?: boolean;
        };
        /** @description A user-created configuration of a [`ChannelType`]. */
        ChannelInstance: {
            created_at?: string | null;
            enabled?: boolean;
            id: string;
            name: string;
            settings?: {
                [key: string]: string;
            };
            type_id: string;
        };
        /** @description Manifest for a channel type — what `channel_type.json` contains. */
        ChannelType: {
            /**
             * @description Native protocol adapter that handles inbound parsing + outbound sending
             *     for this type (e.g. `"twilio"`). Selects code, not config.
             */
            adapter: string;
            description: string;
            id: string;
            name: string;
            /**
             * @description When set, this type is provisioned by a named "connect" flow rather than a
             *     manual settings form — the workshop renders that provider's Connect panel
             *     (e.g. `"metalcraft-gateway"` auto-syncs config from the gateway).
             */
            provisioner?: string | null;
            /**
             * @description API keys this type recommends — surfaced in the key-store UI once any
             *     instance of the type is enabled.
             */
            requires_env?: string[];
            /** @description Per-instance configuration fields the workshop renders into a form. */
            settings?: components["schemas"]["SettingField"][];
            version: string;
        };
        ChatDetail: {
            created_at: string;
            id: string;
            messages: components["schemas"]["ChatMessageWire"][];
            model_name: string;
            persona_slug: string;
        };
        /**
         * @description SSE event wire format. One JSON object per event. The `kind` field
         *     discriminates; payloads vary by kind. Events form a lifecycle:
         *       `turn_started` → (`llm_started` → `llm_completed`
         *                       → `tool_started`* → `tool_completed`*)+
         *                       → `done`
         *     (`tool_started` and `tool_completed` can repeat per LLM step.)
         */
        ChatEvent: {
            /** @enum {string} */
            kind: "turn_started";
            /**
             * @description Diagnostics session directory name for this chat, so the workshop can
             *     deep-link a turn (or a turn error) to its session logs. `None` for a
             *     chat with no active logger — e.g. one reloaded after an agent restart.
             */
            session_id?: string | null;
            turn_index: number;
            user_message: string;
        } | {
            /** @enum {string} */
            kind: "llm_started";
        } | {
            /** Format: int64 */
            duration_ms: number;
            /** @enum {string} */
            kind: "llm_completed";
            messages: components["schemas"]["ChatMessageWire"][];
        } | {
            args: unknown;
            /** @enum {string} */
            kind: "tool_started";
            name: string;
            tool_call_id: string;
        } | {
            /** Format: int64 */
            duration_ms: number;
            /** @enum {string} */
            kind: "tool_completed";
            name: string;
            result: components["schemas"]["ChatMessageWire"];
            tool_call_id: string;
        } | {
            content: string;
            /** @enum {string} */
            kind: "reply";
        } | {
            /** @enum {string} */
            kind: "done";
            reason?: string | null;
            status: string;
        } | {
            code: string;
            /** @enum {string} */
            kind: "error";
            message: string;
            retryable: boolean;
        };
        /**
         * @description Wire form for `metalcraft::AgentMessage` — the in-memory enum isn't
         *     `Serialize`, so we convert before responding. Also used as the on-disk
         *     format for persisted chats, so it derives `Deserialize` too.
         */
        ChatMessageWire: {
            content: string;
            /** @enum {string} */
            role: "user";
        } | {
            content: string;
            /** @enum {string} */
            role: "assistant";
        } | {
            encrypted: string;
            id: string;
            /** @enum {string} */
            role: "reasoning";
        } | {
            args: unknown;
            call_id?: string | null;
            id: string;
            name: string;
            /** @enum {string} */
            role: "tool_call";
        } | {
            call_id?: string | null;
            id: string;
            name: string;
            result: string;
            /** @enum {string} */
            role: "tool_result";
        };
        ChatSummary: {
            created_at: string;
            id: string;
            model_name: string;
            persona_slug: string;
            turn_count: number;
        };
        ChatTurnRequest: {
            message: string;
        };
        CreateChatRequest: {
            model_name?: string | null;
            persona_slug: string;
        };
        CreateGatewayChannelRequest: {
            name: string;
            settings?: {
                [key: string]: string;
            };
            type_id: string;
        };
        /**
         * @description A fully reconstructed session: its `session_info.json` plus an ordered
         *     timeline of every other JSON event file in the directory.
         */
        DiagnosticsSession: {
            id: string;
            session_info?: unknown;
            timeline: components["schemas"]["TimelineEvent"][];
        };
        /** @description One session in the listing (metadata + turn count, no per-turn payloads). */
        DiagnosticsSessionSummary: {
            /** @description Present (and `kind == "flow"`) when produced by a flow run. */
            flow_id?: string | null;
            id: string;
            /** @description "session" for a normal run, "flow" for a flow run. */
            kind?: string | null;
            model_name?: string | null;
            persona_slug?: string | null;
            timestamp: string;
            /** @description Count of `turn_NNN.json` files — how far the run actually got. */
            turn_count: number;
        };
        ErrorResponse: {
            error: string;
        };
        /** @description Result of running one prompt node of a flow. */
        FlowPromptResult: {
            answer?: string | null;
            error?: string | null;
            prompt_index: number;
            /** @description "completed" | "interrupted" | "failed". */
            status: string;
        };
        FlowTemplate: {
            /** @description The raw template flow JSON, ready to be cloned and edited as a new flow. */
            flow: unknown;
            name: string;
            pack_id?: string | null;
            slug: string;
        };
        FlowTemplateSummary: {
            name: string;
            pack_id?: string | null;
            slug: string;
        };
        /**
         * @description One inbound or outbound gateway event.
         *
         *     `channel_id` is `None` when an inbound message matched no enabled channel —
         *     these "unrouted" records are what make the global Network view useful for
         *     diagnosing misconfiguration (e.g. a wrong `integration_id`).
         */
        GatewayEvent: {
            /** @description Message body (truncated to [`MAX_BODY_CHARS`]). */
            body?: string;
            /** @description The matched gateway channel's id, or `None` if unrouted. */
            channel_id?: string | null;
            /** @description The matched gateway channel's name, for display. */
            channel_name?: string | null;
            /** @description Extra context — persona used, error message, etc. */
            detail?: string | null;
            /** @description `"inbound"` or `"outbound"`. */
            direction: string;
            /** @description Sender identifier (phone number for WhatsApp). */
            from?: string | null;
            /** @description Human-readable sender name, when known. */
            from_name?: string | null;
            /**
             * @description Outcome: `routed`, `no_matching_channel`, `signature_rejected`,
             *     `sent`, `send_failed`.
             */
            outcome: string;
            /** @description Channel type / platform, e.g. `"pipestreamr"` or `"twilio"`. */
            platform: string;
            /** @description Upstream integration UUID (PipeStreamr `source_id`), when known. */
            source_id?: string | null;
            /** @description Recipient identifier. */
            to?: string | null;
            /** @description RFC3339 timestamp; filled in by [`record`] if left empty. */
            ts: string;
        };
        /** @description What the workshop Connect panel renders from. */
        GatewayStatus: {
            active_number?: string | null;
            channel?: string | null;
            /** @description The pod has a token (is linked to a Metalcraft ID account). */
            configured: boolean;
            /** @description A local `metalcraft-gateway` channel is enabled and the webhook secret is set. */
            connected: boolean;
            error?: string | null;
            /** @description Whether the pod knows its own public URL (POD_PUBLIC_URL) for the webhook. */
            has_public_url: boolean;
            /** @description The user has registered a personal number on the gateway. */
            registered: boolean;
            /**
             * @description The Inbound Pull long-poll is currently connected and draining. Unlike `connected`
             *     (config present on disk), this is *intrinsic* liveness — it cannot be true while
             *     inbound delivery is actually dead. `false` in push mode (no long-poll runs).
             */
            streaming: boolean;
            /** @description That number is verified — required before connecting. */
            verified: boolean;
            /**
             * @description The gateway's registered inbound webhook (`consumer_webhook_url`) no longer
             *     points at this pod's current URL, so inbound messages are being delivered into
             *     the void. `connected` can be true while this is true — the "green light, dead
             *     pipe" state. Detecting it kicks off a reactive re-register (see `status`).
             */
            webhook_stale: boolean;
        };
        /** @description JSON config schema for a user-defined HTTP API tool. */
        HttpApiToolConfig: {
            body_defaults?: {
                [key: string]: unknown;
            };
            body_mapping?: string;
            body_template?: string | null;
            description: string;
            headers?: {
                [key: string]: string;
            };
            method: string;
            multipart?: null | components["schemas"]["MultipartConfig"];
            name: string;
            /**
             * @description Present only when `body_mapping == "params_nested"`: maps each flat
             *     argument name to a dotted JSON path in the request body (e.g.
             *     `"prompt": "payload.structured_data.params.prompt"`). Lets a tool expose
             *     simple scalar parameters (which OpenAI's function-schema validation
             *     accepts) while still producing a deeply nested JSON body — without the
             *     string-substitution hazards of `body_mapping == "template"`. Arguments
             *     with no entry here are inserted at the top level under their own name.
             *     Absent (optional) arguments are simply skipped, and `body_defaults`
             *     provides the nested base the paths are written onto.
             */
            param_paths?: {
                [key: string]: string;
            };
            parameters: unknown;
            /**
             * @description Marks this tool as a status **poll** (e.g. checking an async job until it
             *     finishes). Polling means calling the same tool with the same arguments
             *     repeatedly on purpose, which would otherwise look like a runaway loop, so
             *     the step guard exempts poll tools from tight loop detection. See
             *     [`crate::guard`].
             */
            poll?: boolean;
            url: string;
        };
        IntegrationPackDetail: {
            api_tools: string[];
            description: string;
            enabled: boolean;
            flow_templates: string[];
            id: string;
            name: string;
            personas: string[];
            requires_env?: string[];
            skills: string[];
            version: string;
        };
        IntegrationPackSummary: {
            api_tools: number;
            description: string;
            enabled: boolean;
            flow_templates: number;
            id: string;
            name: string;
            /** @description Number of personas/skills/api_tools/flow_templates the pack provides. */
            personas: number;
            requires_env?: string[];
            skills: number;
            version: string;
        };
        /**
         * @description A stored key with its **scope** and whether it is managed (platform- or
         *     connection-owned → read-only in the UI). Returned by `GET /api/v1/keys` so
         *     the Keys page can group global keys and per-channel secrets, and lock the
         *     managed ones. `channel_id`/`channel_name` are present only for channel scope.
         */
        KeyEntry: {
            channel_id?: string | null;
            channel_name?: string | null;
            managed: boolean;
            masked: string;
            name: string;
            /** @description `"global"` or `"channel"`. */
            scope: string;
        };
        /** @description The raw value of a key, returned only by the explicit reveal endpoint. */
        KeyRevealResponse: {
            value: string;
        };
        KeyScopeQuery: {
            /** @description When set, target this channel's secret scope instead of global. */
            channel_id?: string | null;
        };
        /**
         * @description A stored API key, exposed to the workshop with its value masked — the
         *     raw secret is never sent over the wire. Used by the load-time snapshot and
         *     the sidebar (global scope only).
         */
        KeySummary: {
            masked: string;
            name: string;
        };
        KeyValueBody: {
            /**
             * @description When set, the key is written to this channel's secret scope instead of
             *     the global namespace.
             */
            channel_id?: string | null;
            value: string;
        };
        MgConnectRequest: {
            /**
             * @description Audience-scoped connection token from the k3 broker, adopted as the
             *     channel's outbound API key. Omitted on the Workshop path.
             */
            connection_token?: string | null;
            /** @description Override for the pod's public URL when `POD_PUBLIC_URL` isn't injected. */
            webhook_base?: string | null;
        };
        MgRegisterRequest: {
            phone_number: string;
        };
        /**
         * @description Config for a `multipart/form-data` upload tool. The argument named by
         *     `file_param` is treated as a local file path (constrained to the upload
         *     root) and sent as the file part `file_field`; all other arguments become
         *     text fields.
         */
        MultipartConfig: {
            /** @description Multipart field name the server expects the file under (e.g. `"file"`). */
            file_field: string;
            /** @description Incoming argument that holds the local file path to upload. */
            file_param: string;
        };
        Persona: {
            description: string;
            name: string;
            /**
             * @description Integration packs this persona is scoped to (by pack id, e.g. "linear").
             *     Every HTTP-API tool provided by an enabled pack listed here is added to
             *     the persona's tool set, so a persona can adopt a whole integration
             *     without enumerating each `<pack>_*` tool by name. Combine with `tools`
             *     for native tools like `load_skill`. See [`Persona::resolved_tool_names`].
             */
            packs?: string[];
            skills?: string[];
            system_prompt: string;
            tools: string[];
            /**
             * @description Optional semantic version (e.g. "1.1.0") for built-in/seed personas.
             *     Drives force-upgrade on startup: when a bundled seed persona's version
             *     is higher than the installed copy's (a missing version counts as 0),
             *     the installed file is overwritten. User-created personas omit this and
             *     are never force-upgraded. See `seed::write_versioned_seeds`.
             */
            version?: string | null;
        };
        PersonaSummary: {
            description: string;
            name: string;
            /**
             * @description Set when this persona is provided by an enabled integration pack.
             *     Local (user-owned) personas omit this.
             */
            pack_id?: string | null;
            /** @description True for pack-provided personas — the workshop disables Save/Delete. */
            read_only?: boolean;
            slug: string;
        };
        ProjectLayout: {
            api_tools_dir: string;
            data_dir: string;
            flows_dir: string;
            personas_dir: string;
            sessions_dir: string;
            skills_dir: string;
        };
        ProjectSnapshot: {
            api_tools: components["schemas"]["ApiToolSummary"][];
            /**
             * @description From the external `metalcraft-flows` crate, which has no `ToSchema`; the
             *     web app doesn't consume this field, so expose it as an opaque object array.
             */
            flows: Record<string, never>[];
            keys: components["schemas"]["KeySummary"][];
            layout: components["schemas"]["ProjectLayout"];
            personas: components["schemas"]["PersonaSummary"][];
            sessions: components["schemas"]["DiagnosticsSessionSummary"][];
            skills: components["schemas"]["SkillSummary"][];
        };
        /**
         * @description A key recommended by one or more *enabled* integration packs (from their
         *     `requires_env`), with whether it currently resolves (key store or env) and
         *     which packs declare it. Drives the "keys these packs still need" list in
         *     the key store UI — `configured: false` is the hint to add it.
         */
        RecommendedKey: {
            configured: boolean;
            /**
             * @description Platform-managed (env-authoritative, e.g. `METALCRAFT_TOKEN` injected into a
             *     provisioned pod). The UI should show it as provided/read-only rather than
             *     prompting the user to paste a value.
             */
            managed: boolean;
            name: string;
            packs: string[];
        };
        ResumeFlowRunRequest: {
            /** @description Optional value to set as the resumed node's `_last` input. */
            data?: unknown;
            /** @description Handle to take (an approval decision, or `"after"` for a wait). */
            handle: string;
        };
        RunFlowRequest: {
            /**
             * @description Values for the flow's declared entry `inputs`. Object of `{ name: value }`;
             *     missing inputs fall back to their declared defaults. Ignored by v1 flows.
             */
            inputs?: unknown;
            model_name?: string | null;
            /**
             * @description Persona to run the flow's prompts as. Defaults to `coding-agent` if
             *     the caller doesn't specify one.
             */
            persona_slug?: string | null;
        };
        RunFlowResponse: {
            flow_id: string;
            prompts: components["schemas"]["FlowPromptResult"][];
        };
        SetEnabledRequest: {
            enabled: boolean;
        };
        /**
         * @description One configurable field in a channel type's per-instance settings schema.
         *     `input_type` is a hint for the workshop form (`text`, `tel`, `password`,
         *     `number`, `persona`, `model`).
         */
        SettingField: {
            help?: string | null;
            input_type?: string;
            key: string;
            label: string;
            placeholder?: string | null;
            required?: boolean;
            /**
             * @description When true this field is a **secret**: its value is persisted to the
             *     channel's secret scope in the key store (`field.key` is the secret name),
             *     never to the instance's plaintext `settings`. The workshop renders it as a
             *     masked, write-only input under the channel's secrets — the raw value never
             *     flows back out. Adapters read it via `key_store::lookup_scoped`.
             */
            secret?: boolean;
        };
        /** @description A full skill (frontmatter description + body). */
        Skill: {
            body: string;
            description: string;
            pack_id?: string | null;
            read_only?: boolean;
            slug: string;
        };
        /** @description Summary of a skill for listings (no body). */
        SkillSummary: {
            description: string;
            /** @description Set when this skill is provided by an enabled integration pack. */
            pack_id?: string | null;
            /** @description True for pack-provided skills — the workshop disables Save/Delete. */
            read_only?: boolean;
            slug: string;
        };
        TimelineEvent: {
            data: unknown;
            file: string;
            kind: string;
        };
        UpdateGatewayChannelRequest: {
            enabled?: boolean;
            name: string;
            settings?: {
                [key: string]: string;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_api_tools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiToolSummary"][];
                };
            };
        };
    };
    get_api_tool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tool name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HttpApiToolConfig"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_api_tool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tool name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HttpApiToolConfig"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_api_tool: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Tool name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_chats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"][];
                };
            };
        };
    };
    post_create_chat: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateChatRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatSummary"];
                };
            };
        };
    };
    get_chat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_chat: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_chat_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description SSE stream of agent-initiated ChatEvent frames */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatEvent"];
                };
            };
        };
    };
    post_chat_turn: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Chat id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatTurnRequest"];
            };
        };
        responses: {
            /** @description SSE stream (text/event-stream) of ChatEvent frames */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["ChatEvent"];
                };
            };
        };
    };
    list_diagnostics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsSessionSummary"][];
                };
            };
        };
    };
    get_diagnostics_session: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Session id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiagnosticsSession"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_flow_runs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flow run summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    get_flow_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flow run id */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Flow run detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_resume_flow_run: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flow run id */
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ResumeFlowRunRequest"];
            };
        };
        responses: {
            /** @description Resumed run */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    list_flow_templates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowTemplateSummary"][];
                };
            };
        };
    };
    get_flow_template: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Template slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FlowTemplate"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_flow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flow id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The saved flow (metalcraft-flows SavedFlow) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_flow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flow id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_flow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flow id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    post_run_flow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Flow id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunFlowRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunFlowResponse"];
                };
            };
        };
    };
    list_gateway_activity: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayEvent"][];
                };
            };
        };
    };
    list_gateway_channels: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelInstance"][];
                };
            };
        };
    };
    post_create_gateway_channel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateGatewayChannelRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelInstance"];
                };
            };
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_gateway_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateGatewayChannelRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_gateway_channel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    put_gateway_channel_enabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEnabledRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_gateway_channel_events: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Channel id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayEvent"][];
                };
            };
        };
    };
    gateway_metalcraft_connect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MgConnectRequest"];
            };
        };
        responses: {
            /** @description Connected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gateway_metalcraft_disconnect: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Disconnected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gateway_metalcraft_register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MgRegisterRequest"];
            };
        };
        responses: {
            /** @description Registered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    gateway_metalcraft_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GatewayStatus"];
                };
            };
        };
    };
    list_gateway_types: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChannelType"][];
                };
            };
        };
    };
    agent_info: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent name, version, and default persona */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_integration_packs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationPackSummary"][];
                };
            };
        };
    };
    get_integration_pack: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pack id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IntegrationPackDetail"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_pack_enabled: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Pack id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEnabledRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_keys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyEntry"][];
                };
            };
        };
    };
    list_recommended_keys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecommendedKey"][];
                };
            };
        };
    };
    put_key: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Key name */
                name: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KeyValueBody"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_key: {
        parameters: {
            query?: {
                /** @description Channel scope for a channel secret */
                channel_id?: string;
            };
            header?: never;
            path: {
                /** @description Key name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    reveal_key: {
        parameters: {
            query?: {
                /** @description Channel scope for a channel secret */
                channel_id?: string;
            };
            header?: never;
            path: {
                /** @description Key name */
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KeyRevealResponse"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_persona: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Persona slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Persona"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_persona: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Persona slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Persona"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_persona: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Persona slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_scheduled_tasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Scheduled follow-ups */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
        };
    };
    delete_scheduled_task: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Task id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_skill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Skill"];
                };
            };
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    put_skill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Skill"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_skill: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Skill slug */
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_snapshot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSnapshot"];
                };
            };
        };
    };
}
